from pathlib import Path
from typing import Dict

from .constants import NODE_CONTAINER, NODE_IMAGE
from .security import env_line, read_env_file, write_private
from .system import CommandRunner


def compose_text(image: str = NODE_IMAGE) -> str:
    return f'''services:
  {NODE_CONTAINER}:
    container_name: {NODE_CONTAINER}
    hostname: {NODE_CONTAINER}
    image: {image}
    restart: always
    network_mode: host
    env_file:
      - .env
    ulimits:
      nofile:
        soft: 1048576
        hard: 1048576
    volumes:
      - /var/log/remnanode:/var/log/remnanode
      - /dev/shm:/dev/shm:rw
'''


def env_text(node_port: int, secret: str) -> str:
    return "# Generated by Remnawave Node Installer. Keep mode 0600.\n" + "\n".join([
        env_line("NODE_PORT", str(node_port)),
        env_line("SECRET_KEY", secret),
        "",
    ])


def write_node_config(node_dir: Path, *, node_port: int, secret: str, image: str, runner: CommandRunner) -> None:
    node_dir.mkdir(parents=True, exist_ok=True)
    write_private(node_dir / ".env", env_text(node_port, secret), mode=0o600)
    compose_file = node_dir / "docker-compose.yml"
    compose_file.write_text(compose_text(image), encoding="utf-8")
    compose_file.chmod(0o644)
    (node_dir / ".image").write_text(image + "\n", encoding="utf-8")
    runner.run(["docker", "compose", "-f", str(compose_file), "config", "--quiet"], timeout=60)


def compose(runner: CommandRunner, node_dir: Path, *args: str, check: bool = True):
    return runner.run(["docker", "compose", "-f", str(node_dir / "docker-compose.yml"), *args], check=check, timeout=600)


def read_node_config(node_dir: Path) -> Dict[str, str]:
    return dict(read_env_file(node_dir / ".env"))
